/* AUTO-GENERATED by scripts/verify_contracts.py from FastAPI OpenAPI.
 * Do not hand edit. Run: python scripts/verify_contracts.py --update
 */

export interface AttachmentReference {
  "document_id": string;
  "path": string;
  "mime_type"?: string | null;
}

export interface AttemptRecord {
  "attempt_id": string;
  "operation_id": string;
  "stage": Stage | "ingestion" | "classification" | "identification" | "parsing" | "ocr" | "extraction" | "normalization" | "reliability" | "comparison" | "review" | "serialization";
  "kind": "primary" | "technical_retry" | "semantic_repair" | "fallback" | "ocr";
  "attempt_number": number;
  "outcome": "SUCCEEDED" | "FAILED" | "INVALID";
  "error_code"?: string | null;
  "provider_adapter"?: string | null;
  "model_identifier"?: string | null;
  "prompt_version"?: string | null;
  "token_usage"?: Record<string, number> | null;
  "latency_ms"?: number | null;
}

export interface AuditRecord {
  "schema_version"?: "1.0-draft";
  "email_id": string;
  "revision": number;
  "previous_revision"?: number | null;
  "email": EmailRecord;
  "classification": ClassificationResult;
  "state": "COMPLETE" | "NEEDS_REVIEW";
  "outcome": "MATCH" | "MISMATCH" | "NOT_APPLICABLE" | null;
  "mismatch_detected": boolean | null;
  "result_summary": string;
  "documents": Array<DocumentReference>;
  "parsers": Array<ParserResult>;
  "extractions": Array<DocumentExtraction>;
  "evidence": Array<FieldEvidence>;
  "partial_result": PartialResult | null;
  "discrepancies": Array<Discrepancy>;
  "review": ReviewCase | null;
  "processing": ProcessingMetadata;
}

export interface ClassificationResult {
  "state": "RESOLVED" | "NEEDS_REVIEW";
  "category": EmailCategory | "document_comparison" | "new_shipping_instruction" | "invoice_query" | "general" | "spam" | null;
  "reason": string;
  "evidence_ids": Array<string>;
  "confidence_indicator"?: "HIGH" | "MEDIUM" | "LOW" | null;
}

export interface Discrepancy {
  "field": "shipper" | "consignee" | "notify_party" | "port_of_loading" | "port_of_discharge" | "container_count" | "gross_weight_kg";
  "si_value": string | number;
  "bl_value": string | number;
}

export interface DocumentExtraction {
  "document_id": string;
  "role": "SI" | "BL";
  "fields": Record<string, ExtractedField>;
}

export interface DocumentReference {
  "document_id": string;
  "role": DocumentRole | "SI" | "BL" | "UNKNOWN";
  "identification_evidence_ids": Array<string>;
}

export type DocumentRole = "SI" | "BL" | "UNKNOWN";

export interface DynamicVerifyRequest {
  "email_id"?: string;
  "si_text": string;
  "bl_text": string;
}

export type EmailCategory = "document_comparison" | "new_shipping_instruction" | "invoice_query" | "general" | "spam";

export interface EmailRecord {
  "email_id": string;
  "sender": string;
  "subject": string;
  "body": string;
  "attachments": Array<AttachmentReference>;
}

export interface ErrorResponse {
  "code": string;
  "message": string;
  "details": Array<string>;
  "retryable": boolean;
  "blocking_emails"?: Array<string> | null;
}

export type EvidenceKind = "text_span" | "table_cell" | "page_region" | "document_metadata" | "processing_error" | "human_review";

export interface EvidenceLocation {
  "section"?: string | null;
  "page"?: number | null;
  "table"?: string | null;
  "row"?: number | null;
  "column"?: number | null;
  "bbox"?: Array<number> | null;
}

export interface ExtractedField {
  "field": "shipper" | "consignee" | "notify_party" | "port_of_loading" | "port_of_discharge" | "container_count" | "gross_weight_kg";
  "reliability": FieldReliability | "NOT_PROCESSED" | "RELIABLE" | "MISSING" | "UNCERTAIN" | "CONFLICTING" | "UNREADABLE";
  "candidates": Array<FieldCandidate>;
  "selected_candidate": number | null;
  "normalized": NormalizedField | null;
  "explanation": string;
}

export interface FieldCandidate {
  "raw_value": string;
  "source_unit"?: string | null;
  "evidence_ids": Array<string>;
}

export interface FieldComparison {
  "field": "shipper" | "consignee" | "notify_party" | "port_of_loading" | "port_of_discharge" | "container_count" | "gross_weight_kg";
  "si_value": string | number;
  "bl_value": string | number;
  "outcome": "MATCH" | "MISMATCH";
  "rule_version": string;
}

export interface FieldCorrection {
  "document_id": string;
  "field": "shipper" | "consignee" | "notify_party" | "port_of_loading" | "port_of_discharge" | "container_count" | "gross_weight_kg";
  "raw_value": string;
  "evidence_ids": Array<string>;
  "rationale": string;
}

export interface FieldEvidence {
  "evidence_id": string;
  "source_type": "email" | "document" | "processing" | "human_review";
  "source_id": string;
  "kind": EvidenceKind | "text_span" | "table_cell" | "page_region" | "document_metadata" | "processing_error" | "human_review";
  "quote"?: string | null;
  "location"?: EvidenceLocation | null;
  "detail"?: string | null;
}

export type FieldReliability = "NOT_PROCESSED" | "RELIABLE" | "MISSING" | "UNCERTAIN" | "CONFLICTING" | "UNREADABLE";

export interface HTTPValidationError {
  "detail"?: Array<ValidationError>;
}

export type LogicalReason = "missing_attachment" | "unreadable_document" | "wrong_or_uncertain_document_type" | "missing_required_value" | "uncertain_result" | "conflicting_candidate_values" | "processing_or_provider_failure";

export interface NormalizedField {
  "field": "shipper" | "consignee" | "notify_party" | "port_of_loading" | "port_of_discharge" | "container_count" | "gross_weight_kg";
  "state": "VALID" | "INVALID" | "NOT_ATTEMPTED";
  "value": string | number | null;
  "rule_version": string | null;
}

export interface ParserResult {
  "document_id": string;
  "status": ParserStatus | "SUCCESS" | "PARTIAL" | "UNREADABLE" | "UNSUPPORTED";
  "text": string | null;
  "usable_for_extraction": boolean;
  "diagnostic_evidence_ids": Array<string>;
  "attempt_ids": Array<string>;
  "raw_text"?: string | null;
  "clean_text"?: string | null;
  "page_count"?: number | null;
  "table_count"?: number | null;
  "is_scanned"?: boolean;
  "error_message"?: string | null;
  "metadata"?: Record<string, string>;
}

export type ParserStatus = "SUCCESS" | "PARTIAL" | "UNREADABLE" | "UNSUPPORTED";

export interface PartialResult {
  "comparisons": Array<FieldComparison>;
  "unresolved_fields": Array<"shipper" | "consignee" | "notify_party" | "port_of_loading" | "port_of_discharge" | "container_count" | "gross_weight_kg">;
}

export interface ProcessingMetadata {
  "technical_attempt_limit"?: number;
  "semantic_attempt_limit"?: number;
  "attempts": Array<AttemptRecord>;
}

export type ReviewAction = "CONFIRM" | "CORRECT";

export interface ReviewCase {
  "review_id": string;
  "state": "OPEN" | "RESOLVED";
  "issues": Array<ReviewIssue>;
}

export interface ReviewIssue {
  "issue_id": string;
  "stage": Stage | "ingestion" | "classification" | "identification" | "parsing" | "ocr" | "extraction" | "normalization" | "reliability" | "comparison" | "review" | "serialization";
  "logical_reason": LogicalReason | "missing_attachment" | "unreadable_document" | "wrong_or_uncertain_document_type" | "missing_required_value" | "uncertain_result" | "conflicting_candidate_values" | "processing_or_provider_failure";
  "evaluation_reason"?: string | null;
  "document_ids": Array<string>;
  "expected_role"?: "SI" | "BL" | null;
  "fields": Array<"shipper" | "consignee" | "notify_party" | "port_of_loading" | "port_of_discharge" | "container_count" | "gross_weight_kg">;
  "evidence_ids": Array<string>;
  "suggested_action": string;
  "recovery_state": "NOT_APPLICABLE" | "UNAVAILABLE" | "EXHAUSTED" | "UNRELIABLE";
  "recovery_detail": string;
  "attempt_ids": Array<string>;
}

export interface ReviewUpdate {
  "review_id": string;
  "expected_revision": number;
  "actor_id": string;
  "action": ReviewAction | "CONFIRM" | "CORRECT";
  "rationale": string;
  "category"?: "document_comparison" | "new_shipping_instruction" | "invoice_query" | "general" | "spam" | null;
  "classification_evidence_ids"?: Array<string>;
  "role_corrections"?: Array<RoleCorrection>;
  "corrections"?: Array<FieldCorrection>;
  "added_evidence"?: Array<FieldEvidence>;
}

export interface RoleCorrection {
  "document_id": string;
  "assigned_role": "SI" | "BL" | "UNKNOWN";
  "evidence_ids": Array<string>;
  "rationale": string;
}

export type Stage = "ingestion" | "classification" | "identification" | "parsing" | "ocr" | "extraction" | "normalization" | "reliability" | "comparison" | "review" | "serialization";

export interface SubmissionRecord {
  "category": "BL_COMPARISON" | "SI_REQUEST" | "INVOICE_QUERY" | "GENERAL" | "SPAM";
  "status": "OK" | "MISMATCH" | "NEEDS_REVIEW";
  "review_reason"?: string | null;
  "has_defect": boolean;
  "defect_fields": Array<"shipper" | "consignee" | "notify_party" | "port_of_loading" | "port_of_discharge" | "container_count" | "gross_weight_kg">;
}

export interface ValidationError {
  "loc": Array<string | number>;
  "msg": string;
  "type": string;
  "input"?: unknown;
  "ctx"?: Record<string, unknown>;
}
