"""Generate and verify frontend TypeScript contracts from FastAPI OpenAPI.

T14-02 implementation decision: the committed OpenAPI snapshot and generated
TypeScript declarations must remain byte-for-byte synchronized with the live
FastAPI application schema.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT / "frontend" / "openapi.json"
TS_PATH = ROOT / "frontend" / "src" / "types" / "api.ts"


def _schema_to_ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "anyOf" in schema:
        parts: list[str] = []
        for part in schema["anyOf"]:
            rendered = _schema_to_ts(part)
            if rendered not in parts:
                parts.append(rendered)
        return " | ".join(parts) if parts else "unknown"
    if "oneOf" in schema:
        return " | ".join(_schema_to_ts(part) for part in schema["oneOf"])
    if "allOf" in schema:
        return " & ".join(_schema_to_ts(part) for part in schema["allOf"])
    kind = schema.get("type")
    if kind == "null":
        return "null"
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        return f"Array<{_schema_to_ts(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema or "additionalProperties" in schema:
        if "properties" in schema:
            required = set(schema.get("required", []))
            body = []
            for key, value in schema["properties"].items():
                optional = "" if key in required else "?"
                body.append(f"  {json.dumps(key)}{optional}: {_schema_to_ts(value)};")
            return "{\n" + "\n".join(body) + "\n}"
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {_schema_to_ts(additional)}>"
        return "Record<string, unknown>"
    return "unknown"


def _component_decl(name: str, schema: dict[str, Any]) -> str:
    if schema.get("type") == "object" or "properties" in schema or "additionalProperties" in schema:
        rendered = _schema_to_ts(schema)
        if rendered.startswith("{\n"):
            return f"export interface {name} {rendered}"
    return f"export type {name} = {_schema_to_ts(schema)};"


def generate() -> tuple[str, str]:
    import sys
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from app import app

    schema = app.openapi()
    openapi_text = json.dumps(schema, indent=2, sort_keys=True) + "\n"
    components = schema.get("components", {}).get("schemas", {})
    header = (
        "/* AUTO-GENERATED by scripts/verify_contracts.py from FastAPI OpenAPI.\n"
        " * Do not hand edit. Run: python scripts/verify_contracts.py --update\n"
        " */\n\n"
    )
    declarations = [_component_decl(name, components[name]) for name in sorted(components)]
    ts_text = header + "\n\n".join(declarations) + "\n"
    return openapi_text, ts_text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--update", action="store_true", help="write current generated contracts")
    args = parser.parse_args()
    openapi_text, ts_text = generate()

    if args.update:
        OPENAPI_PATH.parent.mkdir(parents=True, exist_ok=True)
        TS_PATH.parent.mkdir(parents=True, exist_ok=True)
        OPENAPI_PATH.write_text(openapi_text, encoding="utf-8")
        TS_PATH.write_text(ts_text, encoding="utf-8")
        print(f"Updated {OPENAPI_PATH.relative_to(ROOT)}")
        print(f"Updated {TS_PATH.relative_to(ROOT)}")
        return 0

    failures: list[str] = []
    if not OPENAPI_PATH.exists() or OPENAPI_PATH.read_text(encoding="utf-8") != openapi_text:
        failures.append(str(OPENAPI_PATH.relative_to(ROOT)))
    if not TS_PATH.exists() or TS_PATH.read_text(encoding="utf-8") != ts_text:
        failures.append(str(TS_PATH.relative_to(ROOT)))
    if failures:
        print("CONTRACT DRIFT: " + ", ".join(failures))
        print("Run: python scripts/verify_contracts.py --update")
        return 1
    print("UI-CT-001 PASS: OpenAPI and TypeScript contracts are synchronized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
