from src.models.base import Contract, Text, require
from src.models.ingestion import (
    AttachmentReference,
    Category,
    ClassificationResult,
    EmailCategory,
    EmailRecord,
)
from src.models.document import (
    DocumentReference,
    DocumentRole,
    DocumentRoleType,
    ParserResult,
    ParserStatus,
    ParserStatusType,
    Role,
)
from src.models.evidence import (
    EvidenceKind,
    EvidenceKindType,
    EvidenceLocation,
    EvidenceSourceType,
    FieldEvidence,
)
from src.models.extraction import (
    Canonical,
    DocumentExtraction,
    ExtractedField,
    FIELD_NAMES,
    FieldName,
    FieldReliability,
    FieldReliabilityType,
    FieldStatus,
    FieldCandidate,
    NormalizedField,
    NormalizedGrossWeight,
    validate_canonical,
)
from src.models.comparison import (
    ComparisonOutcome,
    Discrepancy,
    FieldComparison,
    OutcomeType,
    PartialResult,
)
from src.models.review import (
    ActionType,
    FieldCorrection,
    LogicalReason,
    LogicalReasonType,
    RecoveryState,
    ReviewAction,
    ReviewCase,
    ReviewIssue,
    ReviewUpdate,
    RoleCorrection,
    Stage,
    StageType,
)
from src.models.audit import (
    AttemptRecord,
    AttemptTracker,
    AuditRecord,
    AuditState,
    DynamicVerifyRequest,
    ErrorResponse,
    ProcessingMetadata,
    SubmissionRecord,
    WorkflowState,
)

__all__ = [
    # Base
    "Contract",
    "Text",
    "require",
    # Ingestion (T02-01)
    "EmailCategory",
    "Category",
    "AttachmentReference",
    "EmailRecord",
    "ClassificationResult",
    # Document (T02-02)
    "DocumentRole",
    "Role",
    "DocumentRoleType",
    "ParserStatus",
    "ParserStatusType",
    "DocumentReference",
    "ParserResult",
    # Evidence (T02-03)
    "EvidenceKind",
    "EvidenceKindType",
    "EvidenceSourceType",
    "EvidenceLocation",
    "FieldEvidence",
    # Extraction (T02-04)
    "FieldName",
    "FIELD_NAMES",
    "Canonical",
    "validate_canonical",
    "NormalizedGrossWeight",
    "FieldReliability",
    "FieldReliabilityType",
    "FieldStatus",
    "FieldCandidate",
    "NormalizedField",
    "ExtractedField",
    "DocumentExtraction",
    # Comparison (T02-05)
    "ComparisonOutcome",
    "OutcomeType",
    "FieldComparison",
    "Discrepancy",
    "PartialResult",
    # Review (T02-06)
    "LogicalReason",
    "LogicalReasonType",
    "ReviewAction",
    "ActionType",
    "Stage",
    "StageType",
    "RecoveryState",
    "FieldCorrection",
    "RoleCorrection",
    "ReviewIssue",
    "ReviewCase",
    "ReviewUpdate",
    # Audit (T02-07)
    "AuditState",
    "WorkflowState",
    "AttemptRecord",
    "ProcessingMetadata",
    "AttemptTracker",
    "DynamicVerifyRequest",
    "ErrorResponse",
    "SubmissionRecord",
    "AuditRecord",
]
